### ISSUE TITLE
Upload Sample .env.example

### ISSUE THREAD

**Issue by pankajjha** [Moni-2823/projectCampaignManagement#1]
Hi, Please upload sample .env.example

**Comment by Moni-2823** [comment]
Hi,
I am unable to understand what you mean by Please upload sample
.env.example in your repo so that I can execute it
but I am considering it as a readme file is what you wanted

Setting up node server :-
1- git clone - https://github.com/Moni-2823/projectCampaignManagement
2- cd to the folder
3- run- npm install in the terminal
4- After the installation is finished run- npm start
5- The server will be up on port - 8080

Setting up postman :-
1- Find the import button on top left hand side of postman.
2- Click on the link tab.
3- Paste the url  -
https://api.postman.com/collections/19579697-3487db6c-7a2c-4a4e-97b4-d53e0305695a?access_key=PMAT-01GRWZKJ28CDTJEHPM7SV4NHSA
4- Click on continue
5- The new collection Project Campaign Management will be imported to your
workspace.

**Comment by Moni-2823** [comment]
Hi,
DBURL = mongodb://127.0.0.1/projectCampaignManagement
